kind: pipeline
type: exec
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: build
  commands:
    - docker build -t wizether .

- name: deploy
  commands:
    - cd /var/docker/allwize-stack
    - docker-compose stop wizether wizether-worker
    - docker-compose up -d wizether wizether-worker
